sudo: required
dist: xenial
branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.x$/
language: c
cache:
  apt: true
  ccache: true
  directories:
    - '$HOME/.sonar'
    - '$HOME/.cpanm'
addons:
  sonarcloud:
    organization: gdnsd
  apt:
    update: true
    sources:
      - sourceline: "ppa:maxmind/ppa"
    packages:
      - ragel
      - libev-dev
      - liburcu-dev
      - libsodium-dev
      - libunwind8-dev
      - libmaxminddb-dev
      - libsocket6-perl
      - libio-socket-inet6-perl
      - libwww-perl
      - libhttp-daemon-perl
      - libnet-dns-perl
before_install:
  - cpanm -S -n Net::DNS
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
before_script:
  - autoreconf -vif
script: ./qa/travis-build.sh
matrix:
  include:
    - name: "SonarCloud Coverage and Analysis"
      compiler: gcc
      env: GDNSD_TRAVIS_BUILD=sonarcloud
    - name: "GCC - Optimized Build and Test"
      compiler: gcc
      env: GDNSD_TRAVIS_BUILD=optimized
    - name: "GCC - Developer Build and Test"
      compiler: gcc
      env: GDNSD_TRAVIS_BUILD=developer
    - name: "Clang - Optimized Build and Test"
      compiler: clang
      env: GDNSD_TRAVIS_BUILD=optimized
    - name: "Clang - Developer Build and Test"
      compiler: clang
      env: GDNSD_TRAVIS_BUILD=developer
