sudo: required
dist: trusty
branches:
  only:
    - master
language: c
cache:
  - apt
  - ccache
before_install:
  - sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
  - sudo add-apt-repository ppa:jbboehr/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq ragel libev-dev liburcu-dev libunwind8-dev libmaxminddb-dev libsocket6-perl libio-socket-inet6-perl libwww-perl libhttp-daemon-perl lcov
  - gem install coveralls-lcov
before_script:
  - autoreconf -vif
matrix:
  include:
    - compiler: clang
      env: GDNSD_TRAVIS_BUILD=optimized
    - compiler: gcc
      env: GDNSD_TRAVIS_BUILD=coveralls
script:
  - ./qa/travis-build.sh
